export const ADMIN_ROUTE_PATHS = Object.freeze({
  login: "/login",
  dashboard: "/dashboard",
  users: "/users",
  userDetail: "/users/:userId",
  events: "/events",
  invitations: "/invitations",
  invitationDetail: "/invitations/:invitationId",
  templates: "/templates",
  templateNew: "/templates/new",
  templateEdit: "/templates/:templateId",
  payments: "/payments",
  packages: "/packages",
  notifications: "/notifications",
  systemLogs: "/system-logs",
  reports: "/reports",
});
