-- =====================================================================
-- Koupreng initial schema (Postgres / Supabase)
-- =====================================================================
-- Auth is owned by Supabase (auth.users). app_users is a profile table
-- linked to auth.users by uuid. Token tables are removed (Supabase Auth
-- handles password reset / email verification).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------
create type auth_provider as enum ('LOCAL', 'GOOGLE', 'TELEGRAM');
create type user_role     as enum ('ADMIN', 'USER');

-- ---------------------------------------------------------------------
-- Profiles linked to auth.users
-- ---------------------------------------------------------------------
create table public.app_users (
    id              uuid primary key references auth.users(id) on delete cascade,
    email           varchar(255) not null unique,
    full_name       varchar(120) not null,
    auth_provider   auth_provider not null default 'LOCAL',
    provider_id     varchar(255),
    role            user_role not null default 'USER',
    enabled         boolean not null default true,
    token_version   integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    unique (auth_provider, provider_id)
);

-- ---------------------------------------------------------------------
-- Templates
-- ---------------------------------------------------------------------
create table public.templates (
    template_id   bigint generated by default as identity primary key,
    name          varchar(255) not null,
    category      varchar(50),
    thumbnail_url varchar(1000),
    preview_url   varchar(1000),
    is_premium    boolean not null default false,
    status        varchar(20),
    created_at    timestamptz default now()
);

-- ---------------------------------------------------------------------
-- Invitations
-- ---------------------------------------------------------------------
create table public.invitations (
    invitation_id      bigint generated by default as identity primary key,
    user_id            uuid not null references public.app_users(id) on delete cascade,
    template_id        bigint references public.templates(template_id) on delete set null,
    title              varchar(255) not null,
    slug               varchar(255) unique,
    event_type         varchar(50),
    event_date         date,
    event_time         time,
    venue_name         varchar(255),
    venue_address      varchar(1000),
    google_map_url     varchar(1000),
    host_name          varchar(255),
    partner_name       varchar(255),
    groom_name         varchar(255),
    bride_name         varchar(255),
    groom_father_name  varchar(255),
    groom_mother_name  varchar(255),
    bride_father_name  varchar(255),
    bride_mother_name  varchar(255),
    story_text         text,
    language_mode      varchar(20),
    visibility         varchar(20),
    access_password    varchar(255),
    rsvp_deadline      date,
    status             varchar(20),
    created_at         timestamptz default now(),
    updated_at         timestamptz default now()
);

create index idx_invitations_user on public.invitations(user_id);
create index idx_invitations_template on public.invitations(template_id);

-- ---------------------------------------------------------------------
-- Invitation sections
-- ---------------------------------------------------------------------
create table public.invitation_sections (
    section_id     bigint generated by default as identity primary key,
    invitation_id  bigint not null references public.invitations(invitation_id) on delete cascade,
    section_key    varchar(50) not null,
    section_title  varchar(255),
    content_json   jsonb,
    sort_order     integer,
    is_enabled     boolean not null default true
);

create index idx_invitation_sections_invitation on public.invitation_sections(invitation_id);

-- ---------------------------------------------------------------------
-- Media files
-- ---------------------------------------------------------------------
create table public.media_files (
    media_id       bigint generated by default as identity primary key,
    invitation_id  bigint not null references public.invitations(invitation_id) on delete cascade,
    media_type     varchar(50),
    file_url       varchar(1000),
    public_id      varchar(255),
    sort_order     integer,
    is_cover       boolean not null default false,
    created_at     timestamptz default now()
);

create index idx_media_files_invitation on public.media_files(invitation_id);

-- ---------------------------------------------------------------------
-- Guests
-- ---------------------------------------------------------------------
create table public.guests (
    guest_id              bigint generated by default as identity primary key,
    invitation_id         bigint not null references public.invitations(invitation_id) on delete cascade,
    guest_name            varchar(255) not null,
    phone                 varchar(255),
    email                 varchar(255),
    guest_group           varchar(255),
    side_type             varchar(255),
    table_number          varchar(255),
    invite_token          varchar(255) unique,
    qr_code_url           varchar(1000),
    send_status           varchar(50),
    invitation_viewed_at  timestamptz,
    contribution_status   varchar(50),
    total_contributed     numeric(10,2),
    created_at            timestamptz default now()
);

create index idx_guests_invitation on public.guests(invitation_id);

-- ---------------------------------------------------------------------
-- RSVPs
-- ---------------------------------------------------------------------
create table public.rsvps (
    rsvp_id          bigint generated by default as identity primary key,
    invitation_id    bigint not null references public.invitations(invitation_id) on delete cascade,
    guest_id         bigint references public.guests(guest_id) on delete set null,
    response_status  varchar(50),
    attendee_count   integer,
    message          text,
    responded_at     timestamptz
);

create index idx_rsvps_invitation on public.rsvps(invitation_id);

-- ---------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------
create table public.notifications (
    notification_id  bigint generated by default as identity primary key,
    invitation_id    bigint not null references public.invitations(invitation_id) on delete cascade,
    guest_id         bigint references public.guests(guest_id) on delete set null,
    channel          varchar(50),
    subject          varchar(255),
    message_body     text,
    scheduled_at     timestamptz,
    sent_at          timestamptz,
    status           varchar(50)
);

create index idx_notifications_invitation on public.notifications(invitation_id);

-- ---------------------------------------------------------------------
-- Budgets
-- ---------------------------------------------------------------------
create table public.budgets (
    budget_id      bigint generated by default as identity primary key,
    invitation_id  bigint not null unique references public.invitations(invitation_id) on delete cascade,
    total_budget   numeric(12,2),
    notes          text,
    created_at     timestamptz default now(),
    updated_at     timestamptz default now()
);

-- ---------------------------------------------------------------------
-- Budget items
-- ---------------------------------------------------------------------
create table public.budget_items (
    budget_item_id  bigint generated by default as identity primary key,
    budget_id       bigint not null references public.budgets(budget_id) on delete cascade,
    category        varchar(100),
    item_name       varchar(255) not null,
    estimated_cost  numeric(12,2),
    actual_cost     numeric(12,2),
    vendor_name     varchar(255),
    notes           text
);

create index idx_budget_items_budget on public.budget_items(budget_id);

-- ---------------------------------------------------------------------
-- Subscription packages
-- ---------------------------------------------------------------------
create table public.packages (
    package_id        bigint generated by default as identity primary key,
    package_name      varchar(255) not null,
    price             numeric(10,2),
    duration_days     integer,
    max_invitations   integer,
    max_guests        integer,
    features_json     jsonb,
    status            varchar(50)
);

-- ---------------------------------------------------------------------
-- Subscriptions
-- ---------------------------------------------------------------------
create table public.subscriptions (
    subscription_id  bigint generated by default as identity primary key,
    user_id          uuid not null references public.app_users(id) on delete cascade,
    package_id       bigint not null references public.packages(package_id) on delete cascade,
    start_date       timestamptz,
    end_date         timestamptz,
    payment_status   varchar(50),
    is_active        boolean not null default false,
    created_at       timestamptz default now()
);

create index idx_subscriptions_user on public.subscriptions(user_id);
create index idx_subscriptions_package on public.subscriptions(package_id);

-- ---------------------------------------------------------------------
-- Audit logs
-- ---------------------------------------------------------------------
create table public.audit_logs (
    log_id       bigint generated by default as identity primary key,
    user_id      uuid references public.app_users(id) on delete set null,
    action       varchar(255) not null,
    target_type  varchar(100),
    target_id    bigint,
    details      text,
    created_at   timestamptz default now()
);

create index idx_audit_logs_user on public.audit_logs(user_id);

-- ---------------------------------------------------------------------
-- Payment configs
-- ---------------------------------------------------------------------
create table public.payment_configs (
    payment_config_id        bigint generated by default as identity primary key,
    invitation_id            bigint not null unique references public.invitations(invitation_id) on delete cascade,
    provider                 varchar(50),
    payment_mode             varchar(50),
    is_enabled               boolean not null default true,
    is_fixed_amount          boolean not null default false,
    fixed_amount             numeric(12,2),
    min_amount               numeric(12,2),
    max_amount               numeric(12,2),
    currency                 varchar(10),
    allow_anonymous          boolean not null default true,
    organizer_label          varchar(255),
    success_message          text,
    telegram_notify_enabled  boolean not null default false,
    telegram_chat_id         varchar(255),
    created_at               timestamptz default now(),
    updated_at               timestamptz default now()
);

-- ---------------------------------------------------------------------
-- Payment transactions
-- ---------------------------------------------------------------------
create table public.payment_transactions (
    payment_id                  bigint generated by default as identity primary key,
    invitation_id               bigint not null references public.invitations(invitation_id) on delete cascade,
    guest_id                    bigint references public.guests(guest_id) on delete set null,
    payment_config_id           bigint not null references public.payment_configs(payment_config_id) on delete cascade,
    payer_name                  varchar(255),
    payer_message               text,
    merchant_ref_no             varchar(255) unique,
    payway_transaction_id       varchar(255),
    channel                     varchar(50),
    amount                      numeric(12,2) not null,
    currency                    varchar(10) not null,
    qr_payload                  text,
    payment_link                varchar(1000),
    status                      varchar(50),
    requested_at                timestamptz,
    paid_at                     timestamptz,
    expired_at                  timestamptz,
    callback_received           boolean not null default false,
    raw_callback_json           jsonb,
    verification_response_json  jsonb,
    created_at                  timestamptz default now(),
    updated_at                  timestamptz default now()
);

create index idx_payment_tx_invitation on public.payment_transactions(invitation_id);
create index idx_payment_tx_config on public.payment_transactions(payment_config_id);

-- ---------------------------------------------------------------------
-- Payment webhook logs
-- ---------------------------------------------------------------------
create table public.payment_webhook_logs (
    webhook_log_id    bigint generated by default as identity primary key,
    payment_id        bigint references public.payment_transactions(payment_id) on delete set null,
    provider          varchar(50),
    event_type        varchar(100),
    request_headers   text,
    request_body      text,
    received_at       timestamptz default now(),
    processed_status  varchar(50),
    processing_note   text
);

-- ---------------------------------------------------------------------
-- Telegram notifications
-- ---------------------------------------------------------------------
create table public.telegram_notifications (
    telegram_notification_id  bigint generated by default as identity primary key,
    payment_id                bigint not null references public.payment_transactions(payment_id) on delete cascade,
    chat_id                   varchar(255) not null,
    message_text              text not null,
    status                    varchar(50),
    sent_at                   timestamptz,
    response_json             jsonb,
    created_at                timestamptz default now()
);

-- ---------------------------------------------------------------------
-- Organizer payout accounts
-- ---------------------------------------------------------------------
create table public.organizer_payout_accounts (
    payout_account_id  bigint generated by default as identity primary key,
    user_id            uuid not null references public.app_users(id) on delete cascade,
    provider           varchar(50),
    merchant_id        varchar(255),
    merchant_name      varchar(255),
    is_active          boolean not null default true,
    created_at         timestamptz default now(),
    updated_at         timestamptz default now()
);

create index idx_payout_accounts_user on public.organizer_payout_accounts(user_id);

-- ---------------------------------------------------------------------
-- Auto-create app_users row on auth.users insert
-- ---------------------------------------------------------------------
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    insert into public.app_users (id, email, full_name, auth_provider, provider_id)
    values (
        new.id,
        coalesce(new.email, ''),
        coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1)),
        case
            when (new.raw_app_meta_data ->> 'provider') = 'google'   then 'GOOGLE'::auth_provider
            when (new.raw_app_meta_data ->> 'provider') = 'telegram' then 'TELEGRAM'::auth_provider
            else 'LOCAL'::auth_provider
        end,
        new.raw_app_meta_data ->> 'provider_id'
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_auth_user();
