export const TEMPLATES = [
    {
        id: "royal",
        name: "រាជមង្គលអង្គរ (W01)",
        style: "Traditional Gold",
        popular: true,
        image: "/image/a1.png",
        groom: "សុវណ្ណ",
        bride: "សុដាណា",
        dateText: "ថ្ងៃសៅរ៍ ១៩ ធ្នូ ២០២៦",
        targetDate: "2026-12-19T17:00:00+07:00",
        ceremonyTime: "០៩:០០",
        receptionTime: "១៧:០០",
        venueName: "សាលមង្គល រាជវាំង",
        venueAddress: "ផ្លូវព្រះនរោត្តម ខណ្ឌដូនពេញ\nរាជធានីភ្នំពេញ",
        bg: "#f6efe4",
        paper: "#fffaf1",
        color: "#c8a35f",
        accent: "#6f4d24",
        dark: "#21180f",
        label: "WEDDING INVITATION",
        description: "គំរូអាពាហ៍ពិពាហ៍បែបរាជវង្ស កាតបើកដូចគេហទំព័រ មានផ្នែកអញ្ជើញ កម្មវិធី ទីតាំង រូបភាព និង RSVP។",
    },
    {
        id: "garden",
        name: "បុប្ផាភ្នំពេញ (W02)",
        style: "Modern Khmer",
        popular: true,
        image: "/image/a2.png",
        groom: "បញ្ញា",
        bride: "ច័ន្ទនី",
        dateText: "ថ្ងៃអាទិត្យ ២០ ធ្នូ ២០២៦",
        targetDate: "2026-12-20T17:00:00+07:00",
        ceremonyTime: "០៨:៣០",
        receptionTime: "១៨:០០",
        venueName: "សួនមង្គល ភ្នំពេញ",
        venueAddress: "ផ្លូវ ៦០ម៉ែត្រ ខណ្ឌមានជ័យ\nរាជធានីភ្នំពេញ",
        bg: "#f6f2ff",
        paper: "#ffffff",
        color: "#8b5cf6",
        accent: "#4c1d95",
        dark: "#211336",
        label: "MODERN CEREMONY",
        description: "រចនាបថសួនផ្កាដែលមានពណ៌ស្រាល និងអារម្មណ៍ទំនើបសម្រាប់គូស្វាមីភរិយាថ្មី។",
    },
    {
        id: "forest",
        name: "និស្ស័យមង្គល (W03)",
        style: "Luxury Wedding",
        popular: false,
        image: "/image/a7.png",
        groom: "រតនា",
        bride: "ស្រីស",
        dateText: "ថ្ងៃសៅរ៍ ០៧ កុម្ភៈ ២០២៦",
        targetDate: "2026-12-07T17:30:00+07:00",
        ceremonyTime: "១០:០០",
        receptionTime: "១៧:៣០",
        venueName: "សាលអាពាហ៍ពិពាហ៍ អង្គរបៃតង",
        venueAddress: "ផ្លូវជាតិលេខ ៦\nខេត្តសៀមរាប",
        bg: "#eef7ef",
        paper: "#fbfff8",
        color: "#d8b66b",
        accent: "#1d5c38",
        dark: "#0f2d1d",
        label: "FOREST WEDDING",
        description: "រចនាបថបៃតងប្រណិត មានអារម្មណ៍ស្រស់ និងផ្លូវការសម្រាប់ពិធីក្រៅអាគារ។",
    },
    {
        id: "classic",
        name: "មង្គលជ័យ (W04)",
        style: "Classic Style",
        popular: false,
        image: "/image/a4.png",
        groom: "ដារា",
        bride: "មាលា",
        dateText: "ថ្ងៃអាទិត្យ ១៥ មីនា ២០២៦",
        targetDate: "2026-11-15T17:00:00+07:00",
        ceremonyTime: "០៧:៣០",
        receptionTime: "១៧:០០",
        venueName: "សាលមង្គល សេរីសួស្តី",
        venueAddress: "ផ្លូវម៉ៅសេទុង ខណ្ឌចំការមន\nរាជធានីភ្នំពេញ",
        bg: "#fff6f4",
        paper: "#fffafa",
        color: "#dc2626",
        accent: "#7f1d1d",
        dark: "#2d0f0f",
        label: "KHMER WEDDING",
        description: "បែបខ្មែរបុរាណ ប្រើពណ៌ក្រហមនិងមាស សម្រាប់គូដែលចូលចិត្តភាពសាមញ្ញនិងផ្លូវការ។",
    },
    {
        id: "sky",
        name: "ទេវីសួគ៌ា (W05)",
        style: "Royal Khmer",
        popular: false,
        image: "/image/a5.png",
        groom: "វិចិត្រ",
        bride: "ពេជ្រ",
        dateText: "ថ្ងៃសៅរ៍ ២៥ មេសា ២០២៦",
        targetDate: "2026-12-25T18:00:00+07:00",
        ceremonyTime: "០៩:៣០",
        receptionTime: "១៨:០០",
        venueName: "សាលសួគ៌ា Blue Hall",
        venueAddress: "ផ្លូវសហព័ន្ធរុស្ស៊ី\nរាជធានីភ្នំពេញ",
        bg: "#eaf3ff",
        paper: "#f8fbff",
        color: "#f6d98b",
        accent: "#1e3a8a",
        dark: "#0e1d45",
        label: "ROYAL BLUE",
        description: "ពណ៌ខៀវរាជវង្សជាមួយលម្អមាស សមសម្រាប់ពិធីដែលចង់បានអារម្មណ៍ដាច់ដោយឡែក។",
    },
    {
        id: "vintage",
        name: "សិរីមង្គល (W06)",
        style: "Vintage Gold",
        popular: false,
        image: "/image/a6.png",
        groom: "សិរី",
        bride: "ចន្ធា",
        dateText: "ថ្ងៃអាទិត្យ ១៨ តុលា ២០២៦",
        targetDate: "2026-10-18T17:00:00+07:00",
        ceremonyTime: "០៨:០០",
        receptionTime: "១៧:០០",
        venueName: "សាលមង្គល វិមានមាស",
        venueAddress: "ខណ្ឌសែនសុខ\nរាជធានីភ្នំពេញ",
        bg: "#f7f5f1",
        paper: "#ffffff",
        color: "#9f8a5a",
        accent: "#3f3a32",
        dark: "#171510",
        label: "VINTAGE WEDDING",
        description: "ពណ៌មាសចាស់និងអក្សរបែប vintage សម្រាប់កាតដែលមើលទៅស្ងប់ និងស្អាត។",
    },
];

export function getTemplateById(id) {
    return TEMPLATES.find((template) => template.id === id) || TEMPLATES[0];
}
